Jiganesh/Loads-Of-Logic

- FindNumbersWithEvenNumbersOfDigit.java
- TwoSum.java
- TwoSumII.java
Easy Problem solved by from linear search topic
> Easy Problem solved Find Numbers with even length 

- .vscode/settings.json
- README.md
- binarySearch/searchA2DMatrix.java
- concepts/binarySearch/searchInA2DMatrixReturnPosition.java
solved medium problem which returns boolean and position 
Concept contains solution which return position
> solved binary search in matrix

- README.md
- maths/FindNumbersWithEvenNumberOfDigits.py
- stack/Backspace String Compare.py
- stack/Largest Rectangle in Histogram.py
added 2 problems in stack and updated these problems in readme.
> updated stack problems and readme

- .dev/resourcesWorthReading.md
- README.md
- arrays/houseRobber.java
- arrays/rotateArray.java
Solved Problem DP Problem
Changed some content in Resource Worth Reading 
Changed a file name
Updated README.md
> Commit Summary

- README.md
- linkedlist/maximumTwinSumOfALinkedList.py
- strings/capitalizeTheTitle.java
- strings/capitalizeTheTitle.py
- strings/findFirstPalindromicStringInTheArray.py
- strings/longestPalindromeByConcatenatingTwoLetterWords.java
- strings/longestPalindromeByConcatenatingTwoLetterWords.py
longestPalindrome
maximumTwin
solved README updated
added python solution findFirstPalindromicStringInTheArray
> BiWeekly Contest

- arrays/setMatrixZeroes.py
> solved array medium problem 

- trees/insertIntoABinarySearchTree.java
done some changes , have a look.
> faster than 100% , less space than 70%

- arrays/setMatrixZeroes.java
> one more approach added .

- arrays/checkIfEveryRowAndColumnContainsAllNumbers.py
Modified previously uploaded solution
> solved array easy problem

- .dev/allProblemsSolved.py
- README.md
- concepts/dynamicProgramming/possibleSum.py
- dynamicProgramming/bestTimeToBuyAndSellStock.java
- dynamicProgramming/bestTimeToBuyAndSellStock.py
- greedy/gasStation.py
Solved One DP Problem
Added One Concept about dynamicProgramming
Wrote Code that Updates README.md Problem Count Automatically
> Solve Gas Station Greedy Problem

- arrays/contiguousArray.java
> Daily problem , Medium 

- arrays/medianOfTwoSortedArrays.java
Runtime : faster than 40%, 
Hard level problem solved using Priority Queue ( Min-Heap )
> Hard problem.

- kthSmallestElementInBst.java
- trees/converBstToGreaterTree.java
- trees/recover Binary Search Tree.java
Recover BST
All elements in Two BST
Convert BST to Greater Tree
Kth Smallest Element in a BST
> Medium level problem of BST

- trees/MaximumDepthOfBinaryTree.java
Signed-off-by: rajput-hemant <hemant.rajput_cs20@gla.ac.in>
> MaximumDepthOfBinaryTree.java

- recursion/sudokuSolver.java
- recursion/sudokuSolver2.java
sudokuSolver is the solution for the leetcode problem,
sudokuSolver2 is an interactive code, I'll try to add a method to get input for the sudoku board
It's up to you if you want to add sudokuSolver2 or not.
> 37. Sudoku Solver

- greedy/partitionLabels.java
greedy, Two pointer, String.
Faster than 40% java sol.
> DailyProblem Day 21, problem 763

- greedy/smallestStringWithAGivenNumericValue.java
> DailyProblem, Day 22

- README.md
- linkedlist/removeNthNodeFromEndOfList.py
solved linked list with one approach and second apporach I will add later.  The difference index approach ins remaining
> solved linked list remove nth node from end of list

- strings/checkIfaStringContainsAllBinaryCodesOfSizeK.java
Signed-off-by: rajput-hemant <hemant.rajput_cs20@gla.ac.in>
> 1461. Check If a String Contains All Binary Codes of Size K

- linkedlist/addTwoNumbers.js
@Jiganesh this is the JavaScript solution for adding two numbers problem under Linked List.
> add Two Numbers JavaScript solution

- dynamicProgramming/stringcompressionII.cpp
I have added string compression II - LeetCode hard problem in dp folder, please review my changes and merge them under hacktoberfest accepted label. 
Thank you!!
> adding string compression II dp problem

- sorting/quickSort/quickSortAlgorithm.cpp
Added quick sort algorithm in the sorting folder
> created quickSortAlgorithm.cpp
